### ISSUE TITLE
Hey you bastard

### ISSUE THREAD

**Issue by alecsrobespierre** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#117]
We know that you joke with us, return all the money you receive from us or....
![sin titulo](https://cloud.githubusercontent.com/assets/25838002/24186629/d0f78a12-0e9e-11e7-8021-8d368d44e23d.jpg)

**Comment by shonc502** [comment]
What a piece of shit! Dude actually took donations???? I work my ass off to support me and my family and I am given NO hand outs and don't ask either. Because I'm a MAN. You ask people to donate when you had no intention of a JB. You're scum dude. The JB community will never forget you  and not in a good way. I hope all that money was worth it for the whole world to see how much of a greedy person you are. There are people that need money to eat and to pay there bills. Wow!

**Comment by tolikes1** [comment]
Report here https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/104
