### ISSUE TITLE
iPhone 4S 9.3.5 Firmware Keys

### ISSUE THREAD

**Issue by Nihio** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#47]
Since you're jailbroken can you extract and upload them?

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
You need an iBoot exploit to do that.

**Comment by GeoSn0w** [comment]
Keys can only be extracted by accessing the AES Cryptographic engine of the device, the keys are derived using the GUID key which can't be extracted vis Software, therefore you need a low level (iBOOT / SecureROM (BootROM) vulnerability) to turn the device into a key oracle. Nowadays Jailbreaks are using UserLand vulnerabilities because Apple patching these vulns isn't very much of a problem, imagine if the Jailbreak would use an iBOOT Exploit. When Apple patches it, it destroys an important exploit that's is not easily found.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
Also, this is not a real jailbreak. Don't waste your time here; #50 #53 #42 #36 Not to mention anyone with HALF A BRAIN can recognize this is fake. If I'm proven wrong, I'll be happy to rescind my accusation. Until then, F*CK YOU @Brando1235703.

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
