### ISSUE TITLE
IPA works, but there is nothing happens on press GO button

### ISSUE THREAD

**Issue by dennes544** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#96]
![img_0074](https://cloud.githubusercontent.com/assets/4429342/23848843/0428afe4-07ea-11e7-937a-d81c778aefa8.PNG)

**Comment by dennes544** [comment]
@Brando1235703 What the hell is going on?

**Comment by hacks4live** [comment]
Cydia after reboot ?

**Comment by dennes544** [comment]
@hacks4live Nope

**Comment by dennes544** [comment]
Happens just nothing

**Comment by dennes544** [comment]
Our "great" developer just took yalu102 jailbreak, changed offsets to 9.3.4 offsets and he maybe he really trust to himself, but as a Android, iOS, linux and windows developer i can say, ITS NEVER GONNA WORK THIS WAY!!! @Brando1235703 STOP FOOLING PEOPLE, IF YOU HAVE WORKING JAILBREAK, RELEASE IT THEN, IF NOT, DELETE IT FROM GITHUB, STOP IT!

**Comment by dennes544** [comment]
And yeah, you've been creating just storyboards around 2 months, thats really new world record!!!

P.S. for people who never developed anything - create one dynamic storyboard for iPhone and iPad ether can took around 15-20 mins, but no a 2 months

**Comment by hacks4live** [comment]
But why he created different storyboard and not just one ?

**Comment by foundfallon** [comment]
@dennes544, finally! Thanks a lot! I knew it was fake from the beginning when he demonstrated a video back in December.. You're absolutely right in every way!

Thanks!

**Comment by foundfallon** [comment]
@dennes544, read issue #50.. Brandon blocked him, edited and closed issue because the issue #50 exposed a lot about him.. Issue #81 he said he won't release if hate comments increase..

His FAQ, 👊🏻😂

> Q: Will beta 4 install Cydia?
> A: Yes, that's the whole point of the exploit
> Q: Will beta 4 include the exploit?
> A: Yes, my team is currently working on getting Beta 4 out as soon as possible

His README.md ✌🏻😆

> This is a 32 bit only Semi-Tethered Jailbreak for iOS 9.3.5.
> 
> Already supported (Exploit): iPhone 4S, iPad 2, iPad 3.
> 
> Planned Support (Exploit): iPhone 5, iPhone 5C, iPod Touch 5G, iPad 4, iPad Mini.

He spend fucking 3 betas for the fucking UI and here we're having trouble installing it.. The irony here is.. he even accused saurik (cydia and cydia impactor founder) to be held accountable for his fucking .ipa not working..

Here's is the issue #50 

#50 **#50 **BE AWARE! FAKE! **must read****

> I had this Issue with him.. and exposed his real purpose..
> and he replied.. in which he told he sold his "youtube account" to his best friend..
> 
> I made a comment after exposing even further.. but he deleted it.. Proving this guy is Fake!
> 
> He sold his "Youtube Account" to his "best" friend as his "best" friend requested.. and his "best" friend uploaded a fake video.. trying to fool everyone..
> 
> > In the YouTube video (https://www.youtube.com/watch?v=JHpHMQfbr5E&feature=youtu.be) you uploaded..
> > 
> >  Your iPod's MTerminal, says "Kernel version 15.0.0", then I checked the iPhone Wiki Page (https://www.theiphonewiki.com/wiki/Kernel), iOS 9.3.5 is supposed to have Kernel version 15.6.0.(https://twitter.com/qwertyoruiopz/status/698917148144640000), and meanwhile 15.0.0 is for iOS 9.2 and below.. Did you just change the iOS version (http://www.ijailbreak.com/how-to/fake-ios-firmware-version-ios-6/) and try to fool us?﻿
> >  
> >  I bet you're gonna close the issue!
> >  Dare Reply..
> > >
> 
> This is the comment I made..
> 
> This was his reply
> 
> > No, that's not the case at all. I sold my youtube to my best friend back in september, because he wanted an "all ready and created" youtube account. He knows how to spoof jailbreaks and so he did, he posted a video claiming he has a iOS 9.3.5 jailbreak in the works. I have the exploit ready but making a few adjustments before rolling it out to the public.
> 
> **Source:
> ![screen shot 2017-03-07 at 2 07 19 pm](https://cloud.githubusercontent.com/assets/25061677/23704245/015f3374-0415-11e7-8992-7d8c37295a34.png)**
> ￼
> 
> Edit: I made one more comment.. He deleted it..
> 
> If he sold his youtube account in September.. Why is the channel name not changed? Why there's a new "gaming" video under his name?
> ![screen shot 2017-03-07 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/25061677/23704231/edfc41b4-0414-11e7-9353-6afbdef3ff53.png)
> ￼
> 
> This guy has absolutely no idea what he is doing.. He's making 2 different storyboards (iPad,iPhone) and betas just for the storyboard (shows his experience).. I hardly Believe any of his stories anyway.. This guy has no background related to Jailbreak community or any acts at all.. Watch this video (https://www.youtube.com/watch?v=PSuxN005RTM) exposing these kinds of people..
> Watch this too: (https://www.youtube.com/watch?v=8FBkmYYYZ_4&t=35s) Brando getting exposed for the youtube video
> 
> Wait for the FriedAppleTeam (https://twitter.com/friedappleteam).. They’re legit! (https://www.blackhat.com/asia-17/briefings/schedule/#fried-apples-how-to-make-a-jailbreak-5457)
> 
> This is a complete scam!

Well I think it's true.. because he is not a man of his word.. he promised something.. it was on march 9th.. yet here we are still believing in him..

I think the hate is growing because he doesn't do what he says.. with silly reasons..
That's not the case with others.. that's why luca and many others are trusted..

This is a teenager trying to fool us out..
Check it out!! watch this kid getting exposed..!!

https://www.youtube.com/watch?v=QpOWZ4W1Wdg

My Advice.. Leave this leech and pray friedappleteam release a jailbreak for all the devices that are stuck at iOS 9.3.5.. Send the requests.. They're on Twitter.. You know what! They demoed the iOS 9.3.5 jailbreak! Not like this fucking leech.. Alright, stay with them.. Hope they'll release for 32-bit..

March 31.. Peace!

**Comment by bananaNuns** [comment]
https://github.com/osxusr/nalu935

lets hope this one works , i found it on github , can someone that has more knowledge help??? does it have pontential ?

im sorry i comented a couple of times i just want as many ppl as possible to answer me

**Comment by shonc502** [comment]
Dudes a douchebag and a joke
